try {

  
} catch {
  console.log("This Code Still Working");
}
